### ISSUE TITLE
Add filtering by anomaly screening status

### ISSUE THREAD

**Issue by drewthorp** [PublicHealthEngland/canql#25]
As a user I want to be able to screen cases based on if they have anomalies with a certain screening status.
So I can identify cases that have (or have not been screened) and by the outcome of that screening (If they had one)

- Its done when the case can be filtered by a specific screening status (See details in table 1).
- Its done when the case can be filtered by a general screening status in the form Detected, Undetected and Ineligible.

Table 1 :-

Desription | Long form | Short form
---------- | --------- | ----------
Unscreened | unscreened |
Detected: screen +ve FA Scan | FA Detected | FAPOS
Detected: screen +ve combined | Combined Detected | CTPOS
Detected: screen +ve quad | Quad Detected | QTPOS
Undetected: screen -ve FA Scan | FA Undetected | FANEG
Undetected: screen -ve combined | Combined Undetected | CTNEG 
Undetected: screen -ve quad | Quad Undetected | QTNEG
Undetected: early|late screen | nonwindow | NWS
Undetected: incomplete screen | incomplete screen | ICS
Ineligible: late|no booking | ineligible unbooked | INB
Ineligible: early diagnosis | early detected | IED
Declined screening | screen declined | SD
Ineligible: early fetal loss | ineligible early loss | IEFL
Ineligible: early fetal loss (TOP) | ineligible TOP | ITOP
Missed screen | missed screen | MS
Excluded: incomplete data | excluded | EXC

**Comment by joshpencheon** [comment]
Not sure what to make of the short form of "Ineligible: late" being longer than the long form...!
